### ISSUE TITLE
Coverage : only the last class is displayed in SonarQube

### ISSUE THREAD

**Issue by AlexandreRzc** [uartois/sonar-golang#10]
### Description

Only the last class/file of the generated report is displayed in the coverage section in SonarQube

### Steps to Reproduce

0. Generate a coverprofile file on folder with several go files
1. Generate a coverage report with the command : gocov convert cover.out | gocov-xml > coverage.xml
2. Launch Sonar Scanner
3. Look at the coverage section in SonarQube : only the last file/class of the coverage.xml is displayed 
4. Edit the coverage report and remove the last file/class
5. Look at the coverage section in SonarQube : the previous file/class of the deleted file/class is displayed instead

**Comment by danielleberre** [comment]
Thanks for pointing that out. 

There is indeed an issue in the way we deal with the cover files. We need to feed sonar after each file in the report, not at the end of the report. 

We will do our best to provide you a fix ASAP. Sorry for the inconvenience.

**Comment by thibaultfalque** [comment]
Hi,
I just published the bug fix release. Please close the issue if the problem is solved on your side.

Regards,
Thibault.

**Comment by AlexandreRzc** [comment]
It works now : bravo ! :)
