### ISSUE TITLE
Does SonarQube 5.6 compatible with latest artifact ?

### ISSUE THREAD

**Issue by kalagp** [uartois/sonar-golang#22]
I just wanted to know if the current version of plugin is compatible with SonarQube 5.6? . Sonar service isn't starting after placing the Jar file .

**Comment by thibaultfalque** [comment]
Hi, The plugin is compatible with Sonarqube 6+.

**Comment by kalagp** [comment]
How about the 5.6.6 LTS version ? And, do we have some documentation regarding this ??

**Comment by thibaultfalque** [comment]
Hi, 
The plugin is only compatible with Sonarqube 6 and + because I use the framework of 6+. There are differences between 5.6 and 6. 
So for use the plugin the minimum required version is 6.0. You can upgrade your sonarqube instance or wait the next LTS version.
