### ISSUE TITLE
Custom source code check

### ISSUE THREAD

**Issue by Cosby86** [uartois/sonar-golang#28]
Hello all any idea on how to perform custom checks on the code? For example I would check for fmt.Println in the code or looking for any variable with first capital letter in a private method.

Thank you

**Comment by thibaultfalque** [comment]
Hi, 
Thanks you for your question. 
The plugin use gometalinter for generate report. If you want  just add new rules from this tools you can add rules in different properties file (look this PR #13). If you want add rules not from gometalinter the only solution is to modify gometalinter for create new rules. 

@danielleberre Have you any others suggestions ?
