### ISSUE TITLE
Errors importing xml entries

### ISSUE THREAD

**Issue by Cosby86** [uartois/sonar-golang#29]
Hello all,
 when I run SonarScanner I got many of those WARNINGS:

WARN: The key for the message should omit type []byte from declaration of var readBuffer; it will be inferred from the right-hand side is null, issue not saved

What are they? Thank you

**Comment by thibaultfalque** [comment]
Hi, 
This warning is because the issue is not known by the plugin, I can add this rules if you send me the warning. 
More information #12 #13. 

Thanks. 
Thibault.
