### ISSUE TITLE
golint : Lines of code isn't showing in sonarqube

### ISSUE THREAD

**Issue by skalaiyarasan** [uartois/sonar-golang#3]
### Description
golint : Lines of code and history aren't showing in sonarqube

Can you please fix this one

**Comment by thibaultfalque** [comment]
Okey for lines of code. But I don't understand for "history" ? Please could you explain.

**Comment by skalaiyarasan** [comment]
Sorry.. please ignore history .

**Comment by thibaultfalque** [comment]
Hi,
I just published the bug fix release. Please close the issue if the problem is solved on your side.

Regards,
Thibault.

**Comment by skalaiyarasan** [comment]
Thanks Thibault..its working
