### ISSUE TITLE
Skipped tests not shown

### ISSUE THREAD

**Issue by Cosby86** [uartois/sonar-golang#30]
Hello all,
 i enabled the rule "Skipped unit tests should be either removed or fixed". In my code there are few skipped tests but  I don't have any evidences in sonar. How can I found them?

Another question: Do you have any known bug in duplicated code. It seems not working too

**Comment by thibaultfalque** [comment]
Hi, please follow the [instruction](https://github.com/uartois/sonar-golang/blob/master/ISSUE_TEMPLATE.md) for create an issue and add more informations about your problem: Sonarqube Version, Plugin version, plugin configuration etc... 
This rules is in the gometalinter report ? Please post the report.

**Comment by thibaultfalque** [comment]
Duplicated code is not work for the moment.

**Comment by Cosby86** [comment]
It sounds good. thx
