### ISSUE TITLE
How can I disable the shell output result

### ISSUE THREAD

**Issue by Cosby86** [uartois/sonar-golang#31]
Hello all,
 when I run sonar-go I got a lot of INFO and WARN messages on the shell. I would like to add them (or redirect them on file at least). Is there any way for this?

Thanks

**Comment by thibaultfalque** [comment]
Hi, 
Warn messages are probably due to unmanaged rules. Please save your logs and send the file in this thread, so I could add rules.

**Comment by thibaultfalque** [comment]
sonar-scanner >> output.logs redirect the output

**Comment by Cosby86** [comment]
[output.zip](https://github.com/uartois/sonar-golang/files/1316831/output.zip)

I already tried with bash command >> but I forgot the 2>&1 at the end of the bash row.
BTW attached the output log. As you ken see I have thousand WARN an ERROR rows. Can you let me know if I'm doing something wrong?

Thx

**Comment by thibaultfalque** [comment]
Hi, 
I understood the problem. I will correct. 
Can you send the gometalinter report ? 

Thanks.

**Comment by Cosby86** [comment]
[report.zip](https://github.com/uartois/sonar-golang/files/1316905/report.zip)

Thank you. Attached the report. Let me know if I can help you. What did you find?

**Comment by Cosby86** [comment]
Got it. Thank you, let me know when you fixed it.

**Comment by thibaultfalque** [comment]
Please test: https://github.com/uartois/sonar-golang/releases/tag/v1.2.11-rc2

**Comment by Cosby86** [comment]
[output.zip](https://github.com/uartois/sonar-golang/files/1317801/output.zip)
I had the attached issue when I tried to run sonar scanner using the RC2 jar file (I restarted sonar quebe when I copied the new plugin)

**Comment by Cosby86** [comment]
@thibaultfalque do you have any update?

**Comment by thibaultfalque** [comment]
@Cosby86 I'm sorry but I haven't any problems and I don't understand the reason. I will search a solution.

**Comment by thibaultfalque** [comment]
Do you delete the old version of the plugin in plugin directory ?

**Comment by Cosby86** [comment]
Yes I did

**Comment by thibaultfalque** [comment]
It's strange. What is your version of SonarQube ?

**Comment by Cosby86** [comment]
I restarted the server and now it seems working fine := .
Attached the new sonar log. It seems working better. your thoughts?

**Comment by thibaultfalque** [comment]
Yes it's working better but it's not perfect I will add other rules in the next release.

**Comment by Cosby86** [comment]
Awesone. Many thanks

**Comment by danielleberre** [comment]
If the regexp issue is fixed, it might be better to close this issue. 

Support for more rules is an ongoing issue.

**Comment by Cosby86** [comment]
Ok I'll close it. Thank you for your support
