### ISSUE TITLE
Shadowed variables support

### ISSUE THREAD

**Issue by Cosby86** [uartois/sonar-golang#32]
hello all,
 May I ask you to include the support of shadowed variables errors?

GoMetaLinter found this error:

`<error column="0" line="165" message="declaration of "configuration" shadows declaration at line.go:142" severity="warning" source="vetshadow"/>`

IMHO, this is a very critical issue in the code.

**Comment by genez** [comment]
I'm interested in this rule aswell

**Comment by thibaultfalque** [comment]
Hi, 

I will add this rules.

**Comment by Cosby86** [comment]
Thank you very much. Are you planning to add it into the next release?

**Comment by thibaultfalque** [comment]
Please test: https://github.com/uartois/sonar-golang/releases/tag/v1.2.11-rc3

**Comment by Cosby86** [comment]
I'll do it very soon. Thank you

**Comment by Cosby86** [comment]
Hi thibaultfalque, 
I tested the RC3 but it seems doesn't work. In the report I have vetshadow entries but in the Sonar are not reported. Attached the gometalinter report.

[report.zip](https://github.com/uartois/sonar-golang/files/1339838/report.zip)

**Comment by thibaultfalque** [comment]
Can I have the log please ?

**Comment by Cosby86** [comment]
attached. thx
[sonar-output.zip](https://github.com/uartois/sonar-golang/files/1341416/sonar-output.zip)

**Comment by thibaultfalque** [comment]
please test https://github.com/uartois/sonar-golang/tree/v1.2.11-rc4. The problem was the regex.

**Comment by Cosby86** [comment]
It works good. Many thanks
