### ISSUE TITLE
Wrong comment form in sonar-project.properties probably mislead copier.

### ISSUE THREAD

**Issue by jiaoyan2017** [uartois/sonar-golang#38]
### Description

Comments in sonar-project.properties start with the character sequence **//** instead of **#**. If a user only copy the sonar-project.properties as it is in this project, this plugin won't work.

**Comment by thibaultfalque** [comment]
Hi, 
Thanks for your notice. I have fix the problem.

**Comment by thibaultfalque** [comment]
Can you close the issue ?
