### ISSUE TITLE
Changing from LGPL 3.0 to Apache 2.0

### ISSUE THREAD

**Issue by danielleberre** [uartois/sonar-golang#39]
One user of the plugin would like to contribute to the plugin but cannot due to the current license
of the project conflicting with his employer IP policy.

We initially used LGPL for the plugin because it is the license used by the majority of the sonar plugins.

We welcome contributions from the community and as such are willing to change the current license to Apache 2.0.

Changing the license of the plugin requires all committers of the project to agree with that change.

@dthagard @bobintornado @Tvli @mariusstaicu would you agree to change the license of the project to [Apache 2.0](https://opensource.org/licenses/Apache-2.0)?

The change of license would apply in the next release (1.3).

**Comment by dthagard** [comment]
I'm fine with the change.

**Comment by bobintornado** [comment]
Sure, I agree

**Comment by thibaultfalque** [comment]
I agree.

**Comment by danielleberre** [comment]
@Tvli @mariusstaicu it would be nice if we could have your input on that subject.

**Comment by thibaultfalque** [comment]
@znerd @maclav3 @Kernle32DLL do you agree ?

**Comment by znerd** [comment]
I agree.

**Comment by Kernle32DLL** [comment]
@thibaultfalque I agree

**Comment by maclav3** [comment]
I'm ok with this, sorry for the delay

**Comment by danielleberre** [comment]
@Tvli @mariusstaicu It would be nice if we could have your feedback on that issue.

**Comment by Tvli** [comment]
Hi @danielleberre 
Sorry about the long delay, missed this message completely...
I agree with this change.

**Comment by danielleberre** [comment]
Well, it looks like all code contributors agreed with the change (@mariusstaicu contributed a script on the README page). 

So next release 1.3 will be provided under the Apache 2.0 license.

We have to check how to do this properly: released code must stay forever under LGPL 3.0 license, I guess it can be done using an LGPL_3_0 tag on the branches. Need to think about it.

Thanks for your feedback. I am closing the issue now.
