### ISSUE TITLE
Question: Why is this plugin not available through the official SonarQube update center?

### ISSUE THREAD

**Issue by alixwar** [uartois/sonar-golang#44]
There are multiple community supported plugins already, is there a reason why this plugin cannot be installed through SonarQube itself?

**Comment by danielleberre** [comment]
We did not approach yet SonarQube to be listed there. Do you know the requirements to be supported by the update center?

**Comment by danielleberre** [comment]
Found this on SonarQube website:
https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace

It looks like announcing the releases on google group is the way to announce new versions of a plugin.

**Comment by alixwar** [comment]
👍

**Comment by alixwar** [comment]
Is this the same plugin?

https://groups.google.com/forum/m/#!topic/sonarqube/y4RY0V9K8FI

**Comment by alixwar** [comment]
I verified. It is... ☺

**Comment by alixwar** [comment]
Since compatibility starts at version 6.0 it may be available in the update center (I'm still at 5.6.x). Can someone confirm this? If so I close this ticket.

**Comment by danielleberre** [comment]
I just downloaded version 6.7 LTS. Sonar-golang is not available in the marketplace.

**Comment by alixwar** [comment]
I've asked now in the Google Group why the plugin is not available.

**Comment by alixwar** [comment]
@danielleberre  SonarSource say that there has been no request to make it part of the official distribution. I strongly suggest that you do so, otherwise it's just a matter of time before we have a forked duplicate project that is official

**Comment by satlive** [comment]
@alixwar I just asked.

**Comment by danielleberre** [comment]
@alixwar I just asked.

**Comment by thibaultfalque** [comment]
@alixwar we will create a new thread in google group to ask. But before we will try to create a stable 1.2.11 version.

**Comment by thibaultfalque** [comment]
@alixwar 
We have created a new thread in google group for feedback. If it's good the last release 1.2.11-rc13 will become the last official release. 

https://groups.google.com/forum/#!topic/sonarqube/XKLgz29g3zQ

**Comment by alixwar** [comment]
@thibaultfalque Awesome. Thanks for your efforts!
