### ISSUE TITLE
Readme: link a demo

### ISSUE THREAD

**Issue by lkwg82** [uartois/sonar-golang#54]
### Description

To better understand the plugin and what it offers it might be helpful to show a demo analysis. Or just link an existing one.

Thx.

**Comment by danielleberre** [comment]
The plugin brings the analyses performed by regular go tools to the SonarQube code quality platform.

The analyses of popular open source projects are available online:
https://sonarcloud.io/explore/projects

There is no go project analyzed there, but it gives you an idea of the kind of information you can get.

**Comment by lkwg82** [comment]
Thx for answer. Sonarqube I know, but I dont know the golang plugin and how it feels.

**Comment by danielleberre** [comment]
Well, our instance at the uni is private, we have no public reports to show you, but it sort of does not make anything fancy: it just allows to bring tests and code coverage metrics, plus a few linters violations right into SonarQube.

**Comment by thibaultfalque** [comment]
@lkwg82 could you close this issue if the problem is resolved ?
