### ISSUE TITLE
Not reporting Golint errors

### ISSUE THREAD

**Issue by Rahul-Palliyalil** [uartois/sonar-golang#6]
### Description

created report.xml using gometalinter. Ran sonar-scanner and the log says 
"Analysis report generated and Analysis report uploaded". 
I logged into my dashboard to see the results and it says Bugs 0, codesmells 0 and vulnerabilities 0 for my project, which is not true. I have activated most of the Golint rules in my dashboard .  

### Steps to Reproduce

1. gometalinter.v1 ./... --checkstyle > report.xml. (created report.xml . which i placed in my test-reports folder)
2. Ran sonar-scanner
3. Logged into dashboard and saw Bugs 0, codesmells 0 and vulnerabilities 0. It didn't catch any GOlint errors

### Versions

Versions of your sonar installation, gometalinter and go.
sonarQube version - sonarqube-6.3.1
sonar-scanner version - sonar-scanner-3.0.3.778-linux
gometalinterversion - v1
go version - 1.6.2

**Comment by thibaultfalque** [comment]
Hi, 
Thanks for your feeback. 

Could you copy the content of your sonar-project.properties ? 

Regards, 
Thibault.

**Comment by danielleberre** [comment]
Would it be possible to attach the generated report.xml file to the bug report? It would help us reproduce the issue.

**Comment by danielleberre** [comment]
Did you set the reportPath property to your specific location?

```
sonar.golint.reportPath=test-reports/report.xml
```

There should be a message in the log indicating if a report.xml file has been found or not.

**Comment by thibaultfalque** [comment]
hi @Rahul-Palliyalil 
Have you solved your problem ? 

Regards.

**Comment by Rahul-Palliyalil** [comment]
Apologies, for the delay in responding .still having the same issue

So to answer your questions

1. Did you set the reportPath property to your specific location?

Yes, I have created a "sonar-project.properties" file at my project root level. and have the following options set 

sonar.projectKey=peep-new
sonar.projectName=peep-adapter-new
sonar.projectVersion=1.0
sonar.golint.reportPath=report.xml //default
sonar.coverage.reportPath=coverage.xml
sonar.test.reportPath=test.xml //default
sonar.sources=./
sonar.skipPackageDesign=true
sonar.skipDesign=true
sonar.sourceEncoding=UTF-8

so this is pointing to "sonar.golint.reportPath=report.xml", which is picking the reports from test-reports folder

**Comment by danielleberre** [comment]
Could you try with the current release 1.2.5? 

We sanitized the logs so it should be easier know to detect any issue with the config.

**Comment by Rahul-Palliyalil** [comment]
Now i tried to run gometalinter.v1 ./... --checkstyle > report.xml. from root directry of project and with the report.xml that got generated, I ran sonar-scanner. This time it crashed with the following error

"ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=22, lineOffset=2] to [line=22, lineOffset=6]] as it overlaps at least one existing rule"

**Comment by danielleberre** [comment]
We have a basic syntax highlighter for v1 of the plugin (we are working on a more sophisticated one for v2).

Can you guess the 22nd line of which file is producing the problem?

I believe you may have a keyword in a string or something like that here.

**Comment by Rahul-Palliyalil** [comment]
thanks a lot.Let me have a look now

**Comment by Rahul-Palliyalil** [comment]
still failing with the same crash .

java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=22, lineOffset=2] to [line=22, lineOffset=6]] as it overlaps at least one existing rule
        at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.checkOverlappingBoudaries(DefaultHighlighting.java:58)
        at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:118)
        at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
        at fr.univartois.sonargo.highlighter.Colorizer.colorize(Colorizer.java:48)
        at fr.univartois.sonargo.highlighter.HighlighterSensor.lambda$execute$1(HighlighterSensor.java:36)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at fr.univartois.sonargo.highlighter.HighlighterSensor.execute(HighlighterSensor.java:34)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by danielleberre** [comment]
Hum, sorry for that. I thought the issue was occurring when the highlight was declared, it happens when it is "saved".
https://github.com/uartois/sonar-golang/releases/tag/v1.2.7 should prevent this.

**Comment by Rahul-Palliyalil** [comment]
When I had a look at the crash, it seems that it was becasue it was scanning through the external linter package .Well as I don't need this to be scanned i deleted the package and it works .Now the scanning did finish and it showed in the logs , it is generating the analysis report, but when i look at the sonar dashboard nothing has been reported 


INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@500051c5 is used for js
INFO: Sensor CPD Block Indexer (done) | time=38ms
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Calculating CPD for 1 files
INFO: CPD calculation finished
INFO: Analysis report generated in 1180ms, dir size=190 KB
INFO: Analysis reports compressed in 240ms, zip size=105 KB
INFO: Analysis report uploaded in 528ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/peep-new
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://localhost:9000/api/ce/task?id=AVybqfY9h7qOyYUO75b4
INFO: Task total time: 9.430 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 10.349s
INFO: Final Memory: 44M/151M
INFO: ------------------------------------------------------------------------

**Comment by Rahul-Palliyalil** [comment]
![image](https://user-images.githubusercontent.com/3696935/27028221-0e4f1a08-4f5c-11e7-8518-b7f75df43165.png)

**Comment by danielleberre** [comment]
I see no mention of go related sensors in the logs: could you provide us the full logs?

**Comment by Rahul-Palliyalil** [comment]
unfortunately, the scanner is exposing some of our inputs which we can;t share at the moment . So basically this is scanning through the lines of code and just displaying this message

**Comment by Rahul-Palliyalil** [comment]
**The contents of my report.xml is**  


<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0"><file name="src/cmd/main.go"><error column="0" line="35" message="possible formatting directive in Fatal call" severity="error" source="vet"></error><error column="0" line="42" message="possible formatting directive in Fatal call" severity="error" source="vet"></error></file></checkstyle>

**Comment by Rahul-Palliyalil** [comment]
**The contents of my report.xml**

<```
?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0"><file name="src/bumblebee-peep-adapter/cmd/bumblebee-peep-adapter-server/main.go"><error column="0" line="35" message="possible formatting directive in Fatal call" severity="error" source="vet"></error><error column="0" line="42" message="possible formatting directive in Fatal call" severity="error" source="vet"></error></file></checkstyle>

```

**Comment by Rahul-Palliyalil** [comment]
contents of my report.xml

```

<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0"><file name="main.go"><error column="0" line="35" message="possible formatting directive in Fatal call" severity="error" source="vet"></error><error column="0" line="42" message="possible formatting directive in Fatal call" severity="error" source="vet"></error></file></checkstyle>

```

**Comment by thibaultfalque** [comment]
@Rahul-Palliyalil that's all ? 
No more content in the report?

**Comment by Rahul-Palliyalil** [comment]
no, it seems that this is the only content when i create report.xml by running "gometalinter.v1 ./... --checkstyle > report.xml" from root folder of the project.But when i run the same from inside service directory, it will have lots of input  and output values from the code. But still in both the cases it is not showing golint errors in the dashboard

**Comment by danielleberre** [comment]
Do you have lines starting with 

```
 INFO: Sensor GoMetaLinter issues loader sensor [golang]
```

or 

```
INFO: Sensor Go test JUnit loader sensor [golang]
```

or

```
INFO: Sensor Go Highlighter Sensor [golang]
```

?

Those lines indicate that sonar recognized go files and launched the appropriate sensors on them.

**Comment by Rahul-Palliyalil** [comment]
**this is just a sample from the entire report.xml** 

INFO: Scanner configuration file: /opt/sonar/sonar-scanner-3.0.3.778-linux/conf/sonar-scanner.properties
INFO: Project root configuration file: /root/service/sonar-project.properties
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.9.27-moby amd64
INFO: User cache: /root/.sonar/cache
INFO: Load global settings
INFO: Load global settings (done) | time=61ms
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=4ms
INFO: SonarQube server 6.3.1
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=14ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=27ms
INFO: Load active rules
INFO: Load active rules (done) | time=1115ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=109ms
INFO: Publish mode
INFO: Load server rules
INFO: Load server rules (done) | time=589ms
INFO: Initializer GenericCoverageSensor
INFO: Initializer GenericCoverageSensor (done) | time=0ms
INFO: Base dir: /root/service
INFO: Working dir: /root/service/.scannerwork
INFO: Source paths: .
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: 288 files indexed
INFO: Quality profile for go: Golint Rules
INFO: Quality profile for js: Sonar way
INFO: JaCoCoSensor: JaCoCo report not found : /root/service/target/jacoco.exec
INFO: JaCoCoItSensor: JaCoCo IT report not found: /root/service/target/jacoco-it.exec
INFO: Sensor NoSonar Sensor [php]
INFO: Sensor NoSonar Sensor [php] (done) | time=0ms
INFO: Sensor XmlFileSensor [java]
INFO: 5 source files to be analyzed
INFO: 5/5 source files have been analyzed
INFO: Sensor XmlFileSensor [java] (done) | time=227ms
INFO: Sensor JavaScriptSquidSensor [javascript]
INFO: 1 source files to be analyzed
INFO: Sensor JavaScriptSquidSensor [javascript] (done) | time=276ms
INFO: 1/1 source files have been analyzed
INFO: Sensor GoMetaLinter issues loader sensor [golang]
INFO: Parse the file /root/service/report.xml
INFO: Parsing 'GoLint' Analysis Results
INFO: Parsing file /root/service/report.xml
INFO: error for the file main.go
INFO: GoError [line=35, message=possible formatting directive in Fatal call, severity=error, filePath=main.go]
INFO: inputFile null ? false
INFO: Load /key.properties
INFO: loaded 37
INFO: GoError [line=42, message=possible formatting directive in Fatal call, severity=error, filePath=main.go]
INFO: inputFile null ? false
INFO: Sensor GoMetaLinter issues loader sensor [golang] (done) | time=29ms
INFO: Sensor Go Coverage [golang]
INFO: no coverage file in package /root/service/coverage.xml
INFO: no coverage file in package /root/service/.scannerwork/batch-report/coverage.xml
INFO: no coverage file in package /root/service/test-reports/coverage.xml
INFO: Sensor Go Coverage [golang] (done) | time=824ms
INFO: Sensor Go test JUnit loader sensor [golang]
INFO: no junit report
INFO: Sensor Go test JUnit loader sensor [golang] (done) | time=0ms
INFO: Sensor Go Highlighter Sensor [golang]
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
go
INFO: Color the file: main.go
INFO: Line number 1 index start: 0 index end: 7
INFO: Line number 3 index start: 0 index end: 6
INFO: 	"errors" 1
INFO: 	"errors" 8
INFO: 	"errors" -1
INFO: 	"errors" 1
INFO: 	"os" 1
INFO: 	"os" 4
INFO: 	"os" -1
INFO: 	"os" 1
INFO: 	"os/signal" 1
INFO: 	"os/signal" 11
INFO: 	"os/signal" -1
INFO: 	"os/signal" 1
INFO: 	"syscall" 1
INFO: 	"syscall" 9
INFO: 	"syscall" -1
INFO: 	"syscall" 1
INFO: Line number 1 index start: 0 index end: 7
INFO: Line number 3 index start: 0 index end: 6
INFO: 	"strconv" 1
INFO: 	"strconv" 9
INFO: 	"strconv" -1
INFO: 	"strconv" 1
INFO: 	"time" 1
INFO: 	"time" 6
INFO: 	"time" -1
INFO: 	"time" 1
null
null
INFO: Sensor Go Highlighter Sensor [golang] (done) | time=736ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=8ms
INFO: Sensor org.sonar.plugins.javascript.lcov.UTCoverageSensor [javascript]
INFO: Sensor org.sonar.plugins.javascript.lcov.UTCoverageSensor [javascript] (done) | time=0ms
INFO: Sensor org.sonar.plugins.javascript.lcov.ITCoverageSensor [javascript]
INFO: Sensor org.sonar.plugins.javascript.lcov.ITCoverageSensor [javascript] (done) | time=0ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=60ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=26ms
INFO: Sensor CPD Block Indexer
INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@ec7b5de is used for go
INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@ec7b5de is used for js
INFO: Sensor CPD Block Indexer (done) | time=23ms
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Calculating CPD for 1 files
INFO: CPD calculation finished
INFO: Analysis report generated in 1139ms, dir size=190 KB
INFO: Analysis reports compressed in 220ms, zip size=105 KB
INFO: Analysis report uploaded in 467ms
INFO: ANALYSIS SUCCESSFUL
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at
INFO: Task total time: 7.724 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 8.687s
INFO: Final Memory: 44M/166M
INFO: ------------------------------------------------------------------------

**Comment by danielleberre** [comment]
This important information is here:

```
INFO: Sensor GoMetaLinter issues loader sensor [golang]
INFO: Parse the file /root/service/report.xml
INFO: Parsing 'GoLint' Analysis Results
INFO: Parsing file /root/service/report.xml
INFO: error for the file main.go
INFO: GoError [line=35, message=possible formatting directive in Fatal call, severity=error, filePath=main.go]
INFO: inputFile null ? false
INFO: Load /key.properties
INFO: loaded 37
INFO: GoError [line=42, message=possible formatting directive in Fatal call, severity=error, filePath=main.go]
INFO: inputFile null ? false
INFO: Sensor GoMetaLinter issues loader sensor [golang] (done) | time=29ms
```

AFAI understand, GoMetalLinter found one violation and that violation is properly detected by our plugin.

It is strange that it does not show up in the dashboard ...

**Comment by Rahul-Palliyalil** [comment]
do i have to make any changes in the dashboard configuration for this to appear ?

**Comment by danielleberre** [comment]
No. You just need to check that the rules are active, which should be the case.

**Comment by Rahul-Palliyalil** [comment]
![image](https://user-images.githubusercontent.com/3696935/27033771-b22c2786-4f72-11e7-9142-6d67e044457c.png)


this shows around 43 rules are active

**Comment by danielleberre** [comment]
@thibaultfalque any idea? I do not understand what's going on.

**Comment by Rahul-Palliyalil** [comment]
anything with the sonarqube version i have installed maybe ?

**Comment by danielleberre** [comment]
There is something strange happening. We do not support all the violations of GoMetaLinter: we display in that case a warning in the logs.

The current supported rules can be found here:
https://github.com/uartois/sonar-golang/blob/maintenance/src/main/resources/key.properties

Yours, originating from the "vet" tool according to the report, is not supported yet.

It is surprising that no warning is displayed in the logs.

**Comment by thibaultfalque** [comment]
Hi, 
This release add the vet violation, please use this release and check if you have any problems. 
https://github.com/uartois/sonar-golang/releases/tag/v1.2.8

**Comment by Rahul-Palliyalil** [comment]
tried with the new version (reduced logs displayed). still no bugs reported on the dashboard.

INFO: Scanner configuration file: /opt/sonar/sonar-scanner-3.0.3.778-linux/conf/sonar-scanner.properties
INFO: Project root configuration file: /root/service/sonar-project.properties
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.9.27-moby amd64
INFO: User cache: /root/.sonar/cache
INFO: Load global settings
INFO: Load global settings (done) | time=58ms
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=13ms
INFO: SonarQube server 6.3.1
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=113ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=26ms
INFO: Load active rules
INFO: Load active rules (done) | time=858ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=119ms
INFO: Publish mode
INFO: Project key: peep-new
INFO: -------------  Scan peep-adapter-new
INFO: Load server rules
INFO: Load server rules (done) | time=311ms
INFO: Initializer GenericCoverageSensor
INFO: Initializer GenericCoverageSensor (done) | time=0ms
INFO: Base dir: /root/service
INFO: Working dir: /root/service/.scannerwork
INFO: Source paths: .
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: 289 files indexed
INFO: Quality profile for go: Golint Rules
INFO: Quality profile for js: Sonar way
INFO: JaCoCoSensor: JaCoCo report not found : /root/service/target/jacoco.exec
INFO: JaCoCoItSensor: JaCoCo IT report not found: /root/service/target/jacoco-it.exec
INFO: Sensor NoSonar Sensor [php]
INFO: Sensor NoSonar Sensor [php] (done) | time=0ms
INFO: Sensor XmlFileSensor [java]
INFO: 5 source files to be analyzed
INFO: Sensor XmlFileSensor [java] (done) | time=214ms
INFO: 5/5 source files have been analyzed
INFO: Sensor JavaScriptSquidSensor [javascript]
INFO: 1 source files to be analyzed
INFO: 1/1 source files have been analyzed
INFO: Sensor JavaScriptSquidSensor [javascript] (done) | time=332ms
INFO: Sensor GoMetaLinter issues loader sensor [golang]
INFO: Parsing the file /root/service/report.xml
INFO: Parsing 'GoMetaLinter' Analysis Results
INFO: Load /key.properties
INFO: loaded 40
INFO: Sensor GoMetaLinter issues loader sensor [golang] (done) | time=25ms
INFO: Sensor Go Coverage [golang]
INFO: no coverage file in package /root/coverage.xml
INFO: no coverage file in package /root/service/test-reports/coverage.xml
INFO: Sensor Go Coverage [golang] (done) | time=845ms
INFO: Sensor Go test JUnit loader sensor [golang]
INFO: no junit report
INFO: Sensor Go test JUnit loader sensor [golang] (done) | time=0ms
INFO: Sensor Go Highlighter Sensor [golang]
INFO: Sensor Go Highlighter Sensor [golang] (done) | time=507ms
INFO: Sensor Go Metrics Sensor [golang]
INFO: Sensor Go Metrics Sensor [golang] (done) | time=68ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=3ms
INFO: Sensor org.sonar.plugins.javascript.lcov.UTCoverageSensor [javascript]
INFO: Sensor org.sonar.plugins.javascript.lcov.UTCoverageSensor [javascript] (done) | time=0ms
INFO: Sensor org.sonar.plugins.javascript.lcov.ITCoverageSensor [javascript]
INFO: Sensor org.sonar.plugins.javascript.lcov.ITCoverageSensor [javascript] (done) | time=0ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=39ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=35ms
INFO: Sensor CPD Block Indexer
INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@4cb957b8 is used for go
INFO: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer@4cb957b8 is used for js
INFO: Sensor CPD Block Indexer (done) | time=20ms
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Calculating CPD for 1 files
INFO: CPD calculation finished
INFO: Analysis report generated in 1234ms, dir size=192 KB
INFO: Analysis reports compressed in 303ms, zip size=115 KB
INFO: Analysis report uploaded in 68ms
INFO: ANALYSIS SUCCESSFUL
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: Task total time: 6.947 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 7.878s
INFO: Final Memory: 44M/161M
INFO: ------------------------------------------------------------------------

**Comment by danielleberre** [comment]
It is probably because the new rules are not activated.

+ Go on the Quality Profiles page
+ Click on the arrow near the "Create" button
+ Click on "Restore Built-In Profiles"
+ Choose the language (Go)
+ Click on "Restore"

**Comment by Rahul-Palliyalil** [comment]
updated this and reran, still no change in the dashboard

![image](https://user-images.githubusercontent.com/3696935/27072946-06b2a738-501a-11e7-94b3-71803f973326.png)

**Comment by danielleberre** [comment]
Could you check that you have now 45 active rules?

**Comment by Rahul-Palliyalil** [comment]
it says 40 and 7 inactive

**Comment by danielleberre** [comment]
So you need to restore the go profile to activate the new rules, using the procedure above.

Once all the rules are activated, you should see your violation in the dashboard.

**Comment by Rahul-Palliyalil** [comment]
Great, it works now. Thanks a lot
