### ISSUE TITLE
Which release supports sonarqube v5.6 ?

### ISSUE THREAD

**Issue by mohanraj-r** [uartois/sonar-golang#65]
### Description

We have sonarqube v5.6.6 and trying to install the plugin but noticing that the plugin needs v6+.
Since upgrading is not in our immediate plans, can you please let me know the version of the plugin that will work with sonarqube v5.6.6 ?

**Comment by danielleberre** [comment]
Hi @mohanraj-r 

We started the development of the plugin last year directly for sonar v6+. None of the available releases supports sonar v5.6.

**Comment by mohanraj-r** [comment]
Thanks for the clarification
