### ISSUE TITLE
How to change value of cyclomatic complexity?

### ISSUE THREAD

**Issue by dieuhd** [uartois/sonar-golang#68]
I want to change value of **cyclomatic complexity** from 10 to 30.

```xml
	<rule>
		<key>gocyclo:CyclomaticComplexity</key>
		<name>Cyclomatic complexity is high</name>
		<internalKey>gocyclo:CyclomaticComplexity</internalKey>
		<description><![CDATA[<p>The cyclomatic complexity is greater than 10</p>]]>

		</description>
		<severity>MAJOR</severity>
		<cardinality>SINGLE</cardinality>
		<status>READY</status>
		<type>CODE_SMELL</type>
		<tag>complexity</tag>
		<remediationFunction>CONSTANT_ISSUE</remediationFunction>
		<remediationFunctionBaseEffort>10min</remediationFunctionBaseEffort>
	</rule>
```

How to do it?

Thanks

**Comment by thibaultfalque** [comment]
Hi, 
The plugin use the gometalinter. It's not directly the plugin that generate the issues, the plugin read the report of issues generated by gometalinter. 

So if you want change the cyclomatic complexity you must use the `-over` option of the linter [gocyclo](https://github.com/alecthomas/gocyclo), but I don't know how use this option with [gometalinter](https://github.com/alecthomas/gometalinter).

**Comment by thibaultfalque** [comment]
@dieuhd  could you close this issue if the problem is resolved ?

**Comment by dieuhd** [comment]
Resolved.
I modifyed code of golint https://github.com/golang/lint.
