### ISSUE TITLE
Unit Test Reporting not showing

### ISSUE THREAD

**Issue by amitmawkin** [uartois/sonar-golang#7]
### Description

[Description of the issue]
While running this for golang, i could see coverage etc but no unit test report or history

### Content of your sonar-project.properties
sonar.projectKey=abcd
sonar.projectName=api
sonar.projectVersion=1.0
sonar.golint.reportPath=report.xml
sonar.coverage.reportPath=coverage.xml
sonar.test.reportPath=test.xml
sonar.sources=./
sonar.exclusions=*test.go
### Versions

Versions of your sonar installation, gometalinter and go and OS.
6.3.1
1.8.1
macOs Sieraa

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by thibaultfalque** [comment]
Hi,
Thanks for your feeback.
Would it be possible to attach the generated report.xml for the bug report, coverage.xml for the coverage report and test.xml for the test unit report files and the logs ?
It would help us reproduce the issue.

Regards, 
Thibault.

**Comment by amitmawkin** [comment]
Unfortunately it has too much of our internal stuff and would require significant hygiene before I can publish. 
I will try to mess with the code to see if I can fix it on our end and contribute back

**Comment by thibaultfalque** [comment]
Hi, 
Ok I understood.

**Comment by thibaultfalque** [comment]
Hi, 
Do you have this line in log: "no junit report" or a parsing exception ?

**Comment by thibaultfalque** [comment]
ok I understood. I just corrected the problem. Please check.

**Comment by thibaultfalque** [comment]
Is your problem resolved?

**Comment by jhansiabburu** [comment]
I have posted a question on below link, can anyone please help me out resolving the same
https://stackoverflow.com/questions/46587822/not-able-to-import-ios-unit-test-result-to-sonar-qube
