### ISSUE TITLE
Both coverage and unit test reports are not importing into sonarqube

### ISSUE THREAD

**Issue by skalaiyarasan** [uartois/sonar-golang#8]
### Description

report.xml, coverage.xml, test.xml have been generated by sonar-golang git wiki (https://github.com/uartois/sonar-golang). But coverage and unit test reports are not importing into sonarqube. I could see below error for coverage report in scanner logs. But no details about unit test.

====================================
17:15:42.849 INFO: Analyse for /home/bldadm/test/dca-analytics-cobridge/src/github.com/IMS/dca-analytics-cobridge.git/cohandler/coverage.xml
[Fatal Error] coverage-03.dtd:1:3: The markup declarations contained or pointed to by the document type declaration must be well-formed.
17:15:43.121 ERROR: Exception: 
org.xml.sax.SAXParseException: The markup declarations contained or pointed to by the document type declaration must be well-formed.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
====================================
### Content of your sonar-project.properties

sonar.projectKey=go-test
sonar.projectName=go-test
sonar.projectVersion=1.2
sonar.golint.reportPath=report.xml
sonar.coverage.reportPath=coverage.xml
sonar.test.reportPath=test.xml
sonar.sources=./

### Versions

Versions of your sonar installation (server, sonar-scanner), gometalinter, go and OS.

Sonarqube - 6.3.1
Sonar-scanner - sonar-scanner-3.0.2.768-linux
OS - RHEL 7.1
go version go1.8.3 linux/amd64
gometalinter V1
sonar-golang-plugin-1.2.2

### Additional Information

Sample reports may be necessary to reproduce the issue. Please attach if possible reports files (report.xml, coverage.xml, test.xml) corresponding to the feature which is not working as expected.

**Comment by danielleberre** [comment]
It looks like the coverage.xml file is not correctly formed. It would be nice if you could attach it to the bug report, such that we can check on our side what's going on. 

Regarding the tests, it would be nice if you could also attach the test.xml file to allow us to check what's going on.

**Comment by skalaiyarasan** [comment]
[test.docx](https://github.com/uartois/sonar-golang/files/1049750/test.docx)
[coverage.docx](https://github.com/uartois/sonar-golang/files/1049751/coverage.docx)

**Comment by danielleberre** [comment]
hum, that's very strange: the xml file is correctly built.

Do you have access to the internet when you perform the analysis? 

The DTD is available at http://cobertura.sourceforge.net/xml/coverage-03.dtd and the XML parser may launch an exception if it cannot access that DTD.

**Comment by skalaiyarasan** [comment]
Yes.. can access the internet. (proxy has been set in the system)

**Comment by skalaiyarasan** [comment]
One more thing. reports are generated inside the dockers which has Debian GNU/Linux 8 (jessie). 
Sonar -scan is done in out of the docker (base os) which has RHEL 7.1

**Comment by danielleberre** [comment]
Ok, the issue is probably the proxy (we also have one in our uni which causes us some headache).

Did you set the proxy for sonar-scanner?

Java VM does not take into account the system proxy settings. As such, it is necessary to pass it to the VM. 

You can do that by adding the following property to your sonar-project.properties:

```
sonar.web.javaAdditionalOpts=-Dhttps.proxyHost=XXXXXX -Dhttps.proxyPort=YYYY
```

**Comment by skalaiyarasan** [comment]
Thanks..Let me check

**Comment by skalaiyarasan** [comment]
I set proxy in sonar-project.properties. But same issue ..

**Comment by danielleberre** [comment]
hum. 

@thibaultfalque could you disable DTD checking and append a new release of the plugin to that bug report?

I am pretty sure that the issue is that that Java code is not able to access the DTD because you are behind a proxy. By disabling the verification, it should work fine.

If this is really the issue, we may want to add a new property to disable that DTD check in sonar-project.properties.

**Comment by thibaultfalque** [comment]
Hi, 
I published a new version (1.2.3-alpha). 
Please check if the coverage file is parsed. If yes I add this fix for all xml file and add a properties in sonar-project.properties.

**Comment by skalaiyarasan** [comment]
Hi, 

I replaced the plugin with a new version 1.2.3-alpha. I didn't any error from scanner logs. But reports didn't imported into Sonarqube. Also i noticed below info from scanner logs

INFO: Analyse for /home/bldadm/test/dca-analytics-cobridge/src/github.com/IMS/dca-analytics-cobridge.git/cohandler/coverage.xml
INFO: no coverage file in package /home/bldadm/test/dca-analytics-cobridge/src/githup.com/IMS/dca-analytics-cobridge.git/cohandler/.scannerwork/batch-report/coverage.xml

Any thing,  i have to add in sonar-project.properties

**Comment by danielleberre** [comment]
Ok, so the issue is really related to the impossibility to access the DTD.

The 1.2.3-alpha only disabled the DTD validation for coverage.xml. Let us disable also the validation for the other files.

**Comment by skalaiyarasan** [comment]
Ok..Let me know what I have to do after that

**Comment by danielleberre** [comment]
This is strange, since there is no DTD for the xml test report file. It would work properly for that, i.e. you should see one test reported on your dashboard.

**Comment by skalaiyarasan** [comment]
no..i didn't see unit test report in sonarqube dashboard

**Comment by skalaiyarasan** [comment]
Hi ,

I tried to run solar scanner inside of the docker container.  Now i could see that coverage report in dashboard.

**Comment by danielleberre** [comment]
could we get a hand on an archive of your code to reproduce the problem? 

You could for instance send me a temporary link to daniel.leberre@univ-artois.fr to avoid attaching it to the issue and make it visible to everybody.

**Comment by danielleberre** [comment]
Hum, this is strange. As long as the reports and the code are available for the scanner, it should work on your base OS.

**Comment by skalaiyarasan** [comment]
yes. you are correct. When i run scanner inside docker, coverage report got imported into dashboard. but no test report. 

Sorry Daniel. I can't share source code due to company policy.

**Comment by danielleberre** [comment]
ok, no worries. 

Do you see in the log a mention of report.xml file?

**Comment by skalaiyarasan** [comment]
i could see that 

09:14:53.855 DEBUG: Count lines in /home/dca-analytics-cobridge/src/github.hpe.com/IMS/dca-analytics-cobridge.git/cohandler/test.xml
09:14:53.863 INFO: Sensor XML Sensor [xml] (done) | time=494ms
09:14:53.863 INFO: Sensor GoMetaLinter issues loader sensor [golang]
09:14:53.873 INFO: Parse the file report.xml
09:14:53.873 INFO: Parsing 'GoLint' Analysis Results
09:14:53.873 DEBUG: Parsing file /home/dca-analytics-cobridge/src/github.hpe.com/IMS/dca-analytics-cobridge.git/cohandler/report.xml
09:14:53.899 INFO: error for the file cohandler.go
09:14:53.902 INFO: error for the file cohandler_test.go
09:14:53.904 INFO: Load /key.properties
09:14:53.905 INFO: loaded 37
09:14:53.993 DEBUG: 'cohandler.go' generated metadata  with charset 'US-ASCII'
09:14:54.071 DEBUG: 'cohandler_test.go' generated metadata  with charset 'US-ASCII'
09:14:54.077 INFO: Sensor GoMetaLinter issues loader sensor [golang] (done) | time=214ms
09:14:54.077 INFO: Sensor Go Coverage [golang]
09:14:54.081 INFO: Analyse for /home/dca-analytics-cobridge/src/github.hpe.com/IMS/dca-analytics-cobridge.git/cohandler/coverage.xml
09:14:54.117 INFO: LineCoverage [lineNumber=318, hits=1]
09:14:54.117 INFO: LineCoverage [lineNumber=319, hits=1]

**Comment by danielleberre** [comment]
Ok, something went wrong when parsing the report.xml file.

Would it be possible to append the report.xml file to the issue, without modification? We may have a charset issue: we expect the report to be in UTF-8, not US-ASCII.

**Comment by skalaiyarasan** [comment]
Please find the report.xml


[report..docx](https://github.com/uartois/sonar-golang/files/1054467/report.docx)

**Comment by danielleberre** [comment]
@thibaultfalque could you check if GoMetaLinter can force the charset using the command line?

I suspect that the tools (golint, etc) use the system charset (US-ASCII). We would need to force it to UTF-8.

**Comment by thibaultfalque** [comment]
@danielleberre I did not find anything to force the charset from the command line ...

**Comment by skalaiyarasan** [comment]
Still unit test report is not imported into dashboard

**Comment by danielleberre** [comment]
ok, it looks related to #7. I would propose to close this issue and to move the discussion to #7.

**Comment by skalaiyarasan** [comment]
Hi @danielleberre 

v1.2.4

Only first file of the unit tests got imported , not other's unit test

**Comment by danielleberre** [comment]
@thibaultfalque changing the `return` to a `continue` in the files loop is a workaround for that issue.

@skalaiyarasan we noticed that some files referenced in the xml file are not found during the importation, thus causing an error in the importation of the results. We are working on the issue.

**Comment by skalaiyarasan** [comment]
Thanks

**Comment by danielleberre** [comment]
v1.2.5 https://github.com/uartois/sonar-golang/releases/tag/v1.2.5

should fix your problems.

**Comment by skalaiyarasan** [comment]
still same issue

**Comment by danielleberre** [comment]
Could you provide us the logs of sonar-scanner? it should be easier now to see what's going on.

**Comment by skalaiyarasan** [comment]
INFO: Sensor Go Coverage [golang] (done) | time=48ms
INFO: Sensor Go test JUnit loader sensor [golang]
WARN: file not found /home/dca-cm/src/credential-manager/rest
INFO: Sensor Go test JUnit loader sensor [golang] (done) | time=8ms
INFO: Sensor Go Highlighter Sensor [golang]
INFO: Sensor Go Highlighter Sensor [golang] (done) | time=75ms
INFO: Sensor Go Metrics Sensor [golang]
INFO: Sensor Go Metrics Sensor [golang] (done) | time=23ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=4ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=31ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=1ms
INFO: Sensor CPD Block Indexer


====================

find unit-test report from previous comment

**Comment by danielleberre** [comment]
The plugin expect your tests to be in the file `/home/dca-cm/src/credential-manager/rest_test.go`.

**Comment by skalaiyarasan** [comment]
We won't have rest_test.go . But we have three test files with different name,  But package name is rest of these files 

[bldadm@suotblrbld044g rest]$ pwd
/home/dca-cm/src/credential-manager/rest
[bldadm@suotblrbld044g rest]$ ls | grep test
credentialdata_routes_test.go
credential_routes_test.go
resource_routes_test.go
[bldadm@suotblrbld044g rest]$

-----------------------------------
[bldadm@suotblrbld044g rest]$ cat credential_routes_test.go
package rest

**Comment by danielleberre** [comment]
ok. Here is the issue: the junit file does not contain the name of the test file, so we need to infer it.

Up to now, we simple append "_test.go" to the class under test.

It looks like we need something more sophisticated :)

**Comment by danielleberre** [comment]
I guess that the unit test report is different from the one found in previous comments (`test.docx`), which does not include any mention to `/home/dca-cm/src/credential-manager/rest`?

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="1" failures="0" time="571.909" name="github.com/IMS/dca-analytics-cobridge.git/cohandler">
		<properties>
			<property name="go.version" value="go1.8.3"></property>
		</properties>
		<testcase classname="cohandler" name="TestSyncNow" time="571.800"></testcase>
	</testsuite>
</testsuites>
```

**Comment by skalaiyarasan** [comment]
sorry. that was for initial issue file. 

PFA - current issue

[test.docx](https://github.com/uartois/sonar-golang/files/1067253/test.docx)

**Comment by danielleberre** [comment]
hum, there is no references to `credentialdata_routes`, `credential_routes` or `resource_routes` in the junit file.

@thibaultfalque there is maybe an option in `go-junit-report` to make that information visible. If it is not the case, I do not see how we could relate the failing test to the files available in a package ...

**Comment by thibaultfalque** [comment]
Hi, 
There is not option to make information visible. 

So the problem is the report associate all test with the package without any information of filename. 

I have created an [issue](https://github.com/jstemmer/go-junit-report/issues/57) on `go-junit-report`

**Comment by skalaiyarasan** [comment]
Still we didn't get any update for an issue on go-junit-report

**Comment by thibaultfalque** [comment]
Hi, 
I will make changes on the plugin to improve package analysis.

**Comment by skalaiyarasan** [comment]
sure @thibaultfalque

**Comment by skalaiyarasan** [comment]
@thibaultfalque  now its got fixed ?

**Comment by thibaultfalque** [comment]
I apologize for the delay. I just publish the last release 1.2.9 and this release fix the problem. Please try. 
Thanks.

**Comment by skalaiyarasan** [comment]
I used the release 1.2.9. But we are getting below error 

11:20:48.632 INFO: search test function in /home/bldadm/workspace/sonar-dca-cm-docker-test/src/credential-manager/encrypt/encrypt_test.go
11:20:48.636 INFO: ------------------------------------------------------------------------
11:20:48.636 INFO: EXECUTION FAILURE
11:20:48.636 INFO: ------------------------------------------------------------------------
11:20:48.636 INFO: Total time: 6.357s
11:20:48.729 INFO: Final Memory: 46M/398M
11:20:48.729 INFO: ------------------------------------------------------------------------
11:20:48.729 ERROR: Error during SonarQube Scanner execution
java.lang.StringIndexOutOfBoundsException: String index out of range: -19
        at java.lang.String.substring(String.java:1967)
        at fr.univartois.sonargo.gotest.FunctionFinder.searchInLine(FunctionFinder.java:57)
        at fr.univartois.sonargo.gotest.FunctionFinder.lambda$searchFunctionInFile$2(FunctionFinder.java:41)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at fr.univartois.sonargo.gotest.FunctionFinder.searchFunctionInFile(FunctionFinder.java:40)
        at fr.univartois.sonargo.gotest.FunctionFinder.lambda$searchFunction$1(FunctionFinder.java:30)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at fr.univartois.sonargo.gotest.FunctionFinder.searchFunction(FunctionFinder.java:28)
        at fr.univartois.sonargo.gotest.GoTestSensor.execute(GoTestSensor.java:61)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
11:20:48.730 DEBUG: Execution getVersion
11:20:48.731 DEBUG: Execution stop

**Comment by thibaultfalque** [comment]
Do all your test functions start with "Test"?
Because I search all the test functions and I consider that it starts with "Test" and finish by "(", so for example: 
`func TestMax(t *testing.T)`
Here, I find TestMax. 

But  I think fix the problem in the release 1.2.9-beta, if not I add more log for understand the problem.

**Comment by skalaiyarasan** [comment]
Please find below test case.  it starts with Test* pattern 

func TestKeyOnlyInBackup(t *testing.T){
    removeKeyFile()
    copyFileContent("testSamples/static_id_rsa", "testSamples/backup/id_rsa")
...

But its still same issue. It's taking a unit test which has decided with file name

**Comment by thibaultfalque** [comment]
Can you copy the logs ?

**Comment by thibaultfalque** [comment]
I tried to reproduce the problem, but I can not. Me all the tests are displayed even if they are not in a file with the package name.
![capture du 2017-07-02 17-53-58](https://user-images.githubusercontent.com/6603358/27771513-04629ef8-5f50-11e7-8e68-da3ef3c72a5e.png)

**Comment by skalaiyarasan** [comment]
v1.2.9-gamma is working ..thanks

**Comment by thibaultfalque** [comment]
@skalaiyarasan can I close the issue ?

**Comment by skalaiyarasan** [comment]
Yes..we can close this issue.. Thank you so mush @thibaultfalque and @danielleberre

**Comment by introllo** [comment]
Hi all. Wanted to add a comment that I've tested the 1.2.9-gamma build and it fixes this issue for me.  In my case, I have a test.xml file with 24 total tests across 5 test suites. In 1.2.8, only the tests from the first suite are shown (n=5 tests). When running w/1.2.9-gamma, I see all 24 reported. Looking forward to "official" release. Thx.

**Comment by jhansiabburu** [comment]
i have posted a question on below link, please help if anyone has any solution 

https://stackoverflow.com/questions/46587822/not-able-to-import-ios-unit-test-result-to-sonar-qube
